version: "3"

networks:
  infra:
    driver: bridge

services:
  minio:
    restart: always
    hostname: minio
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    networks:
      - infra
    command: server --console-address ":9001" /data
