version: "3"

networks:
  infra:
    driver: bridge

services:
  minio:
    restart: always
    hostname: minio
    container_name: minio
    image: grcorrea/minio
    ports:
      - "9050:9000"
      - "9051:9001"
    volumes:
      - ./minio/data1:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: datalake
      MINIO_SECRET_KEY: datalake
    networks:
      - infra
    command: server --console-address ":9001" /data
