BOT_NAME = 'reclameaqui'
SPIDER_MODULES = ['reclameaqui.spiders']
NEWSPIDER_MODULE = 'reclameaqui.spiders'
USER_AGENT = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0'}
ROBOTSTXT_OBEY = False
#CONCURRENT_REQUESTS = 16
DOWNLOAD_DELAY = 0.25
#CONCURRENT_REQUESTS_PER_DOMAIN = 16
#CONCURRENT_REQUESTS_PER_IP = 16
COOKIES_ENABLED = True
TELNETCONSOLE_ENABLED = True
AUTOTHROTTLE_ENABLED = False
#AUTOTHROTTLE_START_DELAY = 1
#AUTOTHROTTLE_MAX_DELAY = 2
#AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
#AUTOTHROTTLE_DEBUG = False

#HTTPCACHE_ENABLED = True
#HTTPCACHE_EXPIRATION_SECS = 60
#HTTPCACHE_DIR = 'httpcache'
#HTTPCACHE_IGNORE_HTTP_CODES = []
#HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'

FEED_EXPORT_ENCODING = 'utf-8'
FEED_FORMAT = 'jsonlines'
FEED_URI = 'stdout:'
LOG_LEVEL = 'ERROR'
HTTPERROR_ALLOW_ALL = True